### ISSUE TITLE
Reverse Motor Direction Using WPILib

### ISSUE THREAD

**Issue by rajpabari** [theagencyteam3021/FRC2019#24]
At the moment we reversed the direction of the motors by multiplying by -1
But we think there is a built in function in WPILib to tell the talons what to do
So lets configure that

**Comment by rajpabari** [comment]
Maybe .reverse or .setReverse or Inverse or something

**Comment by Kenna-Chase** [comment]
With the differential drive and WPI_TalonSRX we solved this issue.
