### ISSUE TITLE
Improve distance estimation

### ISSUE THREAD

**Issue by rajpabari** [theagencyteam3021/FRC2019#36]
test it with the target and see how accurate we can get

**Comment by rpabari2020** [comment]
@cole

**Comment by rajpabari** [comment]
TODO: next meeting, recalibrate magic numbers from potentiometer readings and figure out why it was 3.996 off in the first place. It doesn't make sense to be adding a constant to our output value

**Comment by rajpabari** [comment]
it's within about a foot all the time and magic numbers gone
