### ISSUE TITLE
No drive base code

### ISSUE THREAD

**Issue by rajpabari** [theagencyteam3021/FRC2019#4]
Need to add this pls

**Comment by kevinmeziere** [comment]
This might help:

https://github.com/FRCTeam3255/Robot2019/tree/master/src/main/java/frc/robot/commands/Drive

**Comment by Kenna-Chase** [comment]
- Created base program in the Robot.java file to run and test motor/motor-controller, and test was successful.

- Then worked to implement a way to controller motor/motor-controller with Xbox joystick. Test was successful. 

- With testing,  came an error where the joystick on Xbox controller was not perfectly center and made the motor move slowly. Fixed the error. 

** All edits occurred in the Robot.java file.
